package com.unifiedhub.app.data.model

import java.time.LocalDate

data class DailyDigest(
    val date: LocalDate,
    val emailCount: Int,
    val smsCount: Int,
    val missedCallCount: Int,
    val calendarEventCount: Int,
    val topEmails: List<TimelineItem>,
    val topMessages: List<TimelineItem>,
    val missedCalls: List<TimelineItem>,
    val upcomingEvents: List<TimelineItem>
) {
    fun toFormattedText(): String = buildString {
        appendLine("═══════════════════════════════════")
        appendLine("  DAILY DIGEST — $date")
        appendLine("═══════════════════════════════════")
        appendLine()

        appendLine("📊 Summary")
        appendLine("  • $emailCount emails received")
        appendLine("  • $smsCount messages received")
        appendLine("  • $missedCallCount missed calls")
        appendLine("  • $calendarEventCount calendar events")
        appendLine()

        if (upcomingEvents.isNotEmpty()) {
            appendLine("📅 Calendar Events")
            upcomingEvents.forEach { event ->
                appendLine("  • ${event.title}")
                appendLine("    ${event.preview}")
            }
            appendLine()
        }

        if (topEmails.isNotEmpty()) {
            appendLine("📧 Recent Emails")
            topEmails.take(5).forEach { email ->
                appendLine("  • ${email.title}")
                appendLine("    From: ${email.contact}")
            }
            appendLine()
        }

        if (topMessages.isNotEmpty()) {
            appendLine("💬 Recent Messages")
            topMessages.take(5).forEach { msg ->
                appendLine("  • ${msg.contact}: ${msg.preview.take(80)}")
            }
            appendLine()
        }

        if (missedCalls.isNotEmpty()) {
            appendLine("📞 Missed Calls")
            missedCalls.forEach { call ->
                appendLine("  • ${call.contact} at ${call.preview}")
            }
            appendLine()
        }

        appendLine("Generated by Unified Hub")
    }
}
